# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b15a253a55cee89a0991fe038e2ded414da0c83ff57735373ee92afa8d253daa0e38013e9bca3b143c78cd6b4dfa4dc540ed51df4fc997e160e08c170d32677

test:
  secret_key_base: 20f14b285338a746fa602df55cf7f4561ef9354adb80ad279f77981c55c553c22a112206d5efb036de4c63dccbb8e70d68ef349c7c60c9b3c3a31951d1990a58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
